/** French overlay for the mock assistant's canned answers, keyed by rule id. */

export const FR_ASSISTANT_ANSWERS: Record<string, string> = {
  "quebec-language":
    "Le Québec est généralement la province présentant le plus de friction pour les entreprises étrangères, et la langue en est la principale raison.\n\nEn vertu de la Charte de la langue française, l'étiquetage de vos produits, l'emballage, les garanties, les modes d'emploi, l'affichage public et votre site Web destiné à la clientèle doivent tous exister en français — et le français doit être affiché de façon au moins aussi évidente que toute autre langue. Une marque de commerce non française sur une devanture doit être accompagnée d'un descriptif français suffisant.\n\nDeux conséquences pratiques :\n\n1. **Prévoyez une révision graphique propre au Québec.** La plupart des entreprises en ont besoin, et elle coûte généralement de 1 500 $ à 8 000 $ CA par famille de UGS, avec un délai de 6 à 12 semaines. Décidez-en avant de finaliser l'emballage pour le reste du Canada : réemballer plus tard coûte davantage que concevoir d'emblée en bilingue.\n2. **Vérifiez le seuil d'effectif de l'OQLF.** Au-delà, vous devez vous inscrire auprès de l'Office québécois de la langue française et mener une démarche de francisation, qui est un programme s'étalant sur plusieurs mois plutôt qu'un simple dépôt.\n\nNotez que la Loi fédérale sur l'emballage et l'étiquetage des produits de consommation exige déjà une identité de produit et une déclaration de quantité nette bilingues *partout* au Canada — une partie du travail bilingue s'applique donc même si vous ne vendez jamais au Québec.",

  labelling:
    "Les obligations canadiennes d'étiquetage proviennent de deux paliers, et il est utile de les distinguer.\n\n**Fédéral (applicable partout).** La Loi sur l'emballage et l'étiquetage des produits de consommation exige l'identité du produit et la déclaration de quantité nette en français et en anglais, les unités métriques, ainsi que le nom et le principal établissement du fournisseur. Pour les aliments, l'ACIA ajoute le tableau de la valeur nutritive, la liste d'ingrédients et les déclarations d'allergènes selon un format bilingue prescrit.\n\n**Provincial.** Le Québec superpose un régime linguistique français nettement plus strict à la base fédérale, visant les garanties, les modes d'emploi et l'affichage plutôt que le seul espace d'étiquetage.\n\nL'erreur la plus courante consiste à traiter l'étiquetage bilingue comme un enjeu propre au Québec, à concevoir un emballage unilingue anglais pour un lancement en Ontario, puis à découvrir l'exigence fédérale à la douane. Planifiez un graphisme bilingue une seule fois, dès le départ : c'est nettement moins cher qu'une seconde série de production.",

  licensing:
    "L'immatriculation au Canada suit une séquence assez prévisible. Pour la plupart des PME étrangères, elle ressemble à ceci :\n\n1. **Choisissez votre structure.** Immatriculez votre société étrangère existante de façon extraprovinciale, ou constituez une filiale fédérale sous le régime de la LCSA que vous immatriculerez ensuite dans chaque province où vous exercez. La voie fédérale coûte plus cher au départ, mais elle se transpose mieux d'une province à l'autre.\n2. **Nommez un fondé de pouvoir ou un agent aux fins de signification.** Chaque province exige un représentant local doté d'une adresse physique dans la province. Une boîte postale ne suffit pas.\n3. **Obtenez un numéro d'entreprise de l'ARC.** C'est la colonne vertébrale : vos comptes fiscaux, de paie et d'importation-exportation s'y rattachent. Généralement délivré en quelques jours ouvrables.\n4. **Ouvrez le compte de programme d'importation-exportation (RM)** avant l'arrivée de votre premier envoi à la frontière.\n5. **Inscrivez-vous à la taxe de vente** — TVH en Ontario, TPS plus une TVP distincte en Colombie-Britannique, TPS seulement en Alberta, et TPS plus TVQ auprès de Revenu Québec au Québec.\n6. **Inscrivez-vous auprès de la commission provinciale des accidents du travail** avant l'entrée en fonction de votre premier employé.\n\nLes licences municipales s'ajoutent à tout cela et varient selon la ville et la catégorie. Ouvrez le guide des provinces pour voir les éléments propres à chaque province sélectionnée, avec les délais et les frais.",

  tax:
    "Le traitement de la taxe de vente diffère suffisamment d'une province à l'autre pour influencer le choix de votre point d'entrée.\n\n- **Ontario** — TVH de 13 %, un taux harmonisé unique perçu au point de vente.\n- **Colombie-Britannique** — TPS de 5 % plus TVP de 7 %, administrées séparément. La TVP s'applique à certains intrants qui seraient récupérables sous la TVH : votre coût effectif dépasse donc les 12 % affichés.\n- **Alberta** — TPS de 5 % seulement. Aucune taxe de vente provinciale, ce qui en fait la province la plus propre pour tester la sensibilité au prix des consommateurs.\n- **Québec** — TPS de 5 % plus TVQ de 9,975 %, la TVQ étant administrée par Revenu Québec plutôt que par l'ARC, d'où des déclarations distinctes.\n\nLe seuil de petit fournisseur de 30 000 $ CA s'applique sur quatre trimestres civils consécutifs. S'inscrire volontairement sous ce seuil vaut souvent la peine, car cela permet de récupérer les crédits de taxe sur les intrants liés aux frais de démarrage.\n\nQuant aux droits de douane : si vous fabriquez aux États-Unis ou au Mexique, vérifiez les règles d'origine de l'ACEUM avant de présumer d'un traitement préférentiel — ce sont les exigences de certification, plus que les taux, qui prennent les entreprises au dépourvu.",

  partners:
    "Pour une première entrée, le choix se pose généralement entre un distributeur et un agent à commission, et il dépend du degré de contrôle souhaité.\n\n**Les distributeurs** prennent possession de vos marchandises, ce qui élimine votre risque de fonds de roulement et de crédit, mais vous prive aussi de visibilité sur les clients finaux et sur les prix. Ils s'attendent généralement à l'exclusivité sur un territoire défini. Négociez d'abord un territoire restreint — l'Ontario plutôt que tout le Canada — afin qu'un mauvais appariement ne bloque pas l'ensemble du pays.\n\n**Les agents à commission** vous gardent plus près du marché et coûtent moins cher au départ, mais vous assumez vous-même les stocks, les créances et le recouvrement. Cela convient aux produits interentreprises et industriels, où un petit nombre de relations d'approvisionnement compte davantage que la couverture en tablette.\n\nQuel que soit votre choix, prévoyez un budget distinct pour un courtier en douane et un prestataire logistique : les distributeurs se chargent rarement du dédouanement pour vous.\n\nLa page des partenaires présente des options évaluées, filtrables par province et par type. « Demander une présentation » les signale à l'équipe de Northgate.",

  costs:
    "Un budget réaliste de première année pour une entrée dans une seule province se répartit en quatre postes.\n\n**Immatriculation et frais juridiques** — de 3 000 $ à 12 000 $ CA. Les frais d'immatriculation provinciale eux-mêmes sont modestes (de 275 $ à 380 $ CA) ; l'essentiel du poste couvre le travail juridique de structuration, les ententes de distribution et les arrangements de fondé de pouvoir.\n\n**Conformité et étiquetage** — de 2 000 $ à 15 000 $ CA selon le nombre de UGS. Si le Québec est visé, majorez ce poste : la révision graphique en français coûte à elle seule de 1 500 $ à 8 000 $ CA par famille de UGS.\n\n**Mise en place logistique** — de 5 000 $ à 20 000 $ CA pour établir le courtage en douane, l'entreposage sous douane initial et l'intégration au prestataire logistique, avant les coûts par envoi.\n\n**Développement du marché** — la fourchette la plus large, de 10 000 $ à plus de 100 000 $ CA, couvrant les frais de référencement, les salons, les honoraires d'agents et le marketing.\n\nUn ordre de grandeur prudent pour un projet pilote dans une seule province se situe entre 25 000 $ et 60 000 $ CA, avant les stocks. Ajouter le Québec en même temps augmente généralement le poste de conformité de 40 à 60 %.",

  "province-choice":
    "Le choix d'une province d'entrée dépend surtout du point de départ de votre chaîne d'approvisionnement et de l'identité de votre acheteur.\n\n**L'Ontario** est le choix par défaut. Environ 39 % des Canadiens y vivent, la région du Grand Toronto absorbe plus de biens de consommation importés que toute autre région métropolitaine, et les sièges sociaux se concentrent à Toronto. Concurrence la plus forte, mais signal de demande le plus rapide.\n\n**La Colombie-Britannique** s'impose si vous expédiez depuis l'Asie-Pacifique. Vancouver traite un volume de conteneurs supérieur à celui de tous les autres ports canadiens réunis, et le transit depuis Shanghai ou Busan est de 5 à 8 jours plus court qu'en passant par l'est. Le régime de TVP en est la contrepartie.\n\n**L'Alberta** offre l'environnement fiscal le plus léger : taux des sociétés de 8 %, aucune TVP. Son économie se concentre dans l'énergie, l'agriculture et la logistique, et les achats interentreprises passent par un ensemble relativement restreint de relations d'approvisionnement à Calgary et à Edmonton. Un seul agent local solide y surpasse souvent un vaste réseau de distributeurs.\n\n**Le Québec** est le deuxième marché en importance, mais il comporte la charge de conformité la plus lourde en raison du régime linguistique français. Rarement la bonne première province, sauf si vous disposez déjà de capacités francophones.\n\nUne séquence courante consiste à commencer par l'Ontario, puis la province correspondant à votre logistique, et enfin le Québec lorsque l'économie de l'emballage justifie le travail de traduction.",

  timeline:
    "Pour une entrée simple dans une seule province, prévoyez **de trois à cinq mois** entre la décision et la première vente.\n\nVoici comment cela s'enchaîne :\n\n- **Semaines 1–2** — décision de structure, approbation de dénomination le cas échéant (la Colombie-Britannique l'exige avant l'immatriculation).\n- **Semaines 2–6** — immatriculation extraprovinciale. L'Ontario prend de 2 à 4 semaines, la Colombie-Britannique de 3 à 5, l'Alberta de 1 à 3, le Québec de 3 à 6.\n- **Semaines 3–4** — numéro d'entreprise de l'ARC et comptes de taxe de vente. Ces démarches sont rapides, souvent quelques jours, mais elles supposent que l'entité existe déjà.\n- **Semaines 4–12** — révision de l'étiquetage et de l'emballage. C'est généralement le chemin critique, surtout si les exigences françaises du Québec sont en jeu.\n- **Semaines 8–16** — ententes de distribution, courtage en douane et intégration logistique, qui peuvent se dérouler en parallèle de l'étiquetage.\n\nLes deux facteurs qui font le plus souvent dérailler le calendrier sont les révisions graphiques d'emballage et les licences municipales dans les villes aux files d'attente plus lentes. Amorcez les deux plus tôt que nécessaire.",

  employment:
    "L'embauche au Canada est réglementée par province : les obligations se rattachent donc au lieu de travail de l'employé plutôt qu'au lieu d'immatriculation de votre entité.\n\nAvant votre première embauche dans une province, il vous faudra un compte de paie (RP) auprès de l'ARC, une inscription auprès de la commission des accidents du travail de cette province — CSPAAT en Ontario, WorkSafeBC, WCB Alberta, CNESST au Québec — ainsi qu'une paie configurée pour les retenues au titre du RPC, de l'AE et de l'impôt sur le revenu.\n\nLes normes du travail sont provinciales et diffèrent sensiblement quant aux délais de préavis, aux seuils d'heures supplémentaires et aux jours fériés. Le Québec va plus loin : la documentation d'emploi et les communications internes doivent généralement être disponibles en français.\n\nSi vous mutez du personnel plutôt que d'embaucher localement, le volet des personnes mutées à l'intérieur d'une société sous l'ACEUM ou la catégorie générale dispensée d'EIMT constituent habituellement les voies à explorer ; il vaut la peine d'obtenir tôt un avis spécialisé en immigration, car les délais de traitement varient considérablement selon le pays de dépôt.",

  fallback:
    "Je peux vous aider à y réfléchir. Voici les sujets sur lesquels je dispose des renseignements les plus utiles :\n\n- **Immatriculation et licences** — ce qu'il faut déposer, dans quel ordre, et combien de temps prend chaque étape\n- **Taxes de vente** — les différences entre TVH, TPS, TVP et TVQ selon la province, et leur incidence sur vos prix\n- **Étiquetage et conformité bilingue** — exigences fédérales et régime linguistique français plus strict du Québec\n- **Choix d'une province** — associer votre chaîne d'approvisionnement et votre acheteur au bon point d'entrée\n- **Partenaires** — quand un distributeur vaut mieux qu'un agent à commission, et quoi négocier\n- **Coûts et délais** — budgets réalistes de première année et séquence semaine par semaine\n\nPourriez-vous m'en dire davantage sur ce que vous cherchez à décider ? Si vous mentionnez votre type de produit et les provinces envisagées, je pourrai être plus précis.",
};

export const FR_SUGGESTED_QUESTIONS = [
  "Dans quelle province devrions-nous entrer en premier ?",
  "Quelles sont les exigences d'étiquetage en français au Québec ?",
  "Quelles licences nous faut-il en Ontario ?",
  "Quel budget prévoir pour la première année ?",
  "Combien de temps prend l'immatriculation au total ?",
  "Devrions-nous choisir un distributeur ou un agent local ?",
];

/** French keyword sets, so matching works on French questions too. */
export const FR_KEYWORDS: Record<string, string[]> = {
  "quebec-language": ["québec", "quebec", "français", "francais", "langue", "bilingue", "oqlf", "loi 14", "loi 96", "montréal", "montreal", "francisation"],
  labelling: ["étiquet", "etiquet", "emballage", "ingrédient", "ingredient", "valeur nutritive", "graphisme", "paquet"],
  licensing: ["licence", "permis", "immatricul", "inscription", "constituer", "constitution", "entité", "entite", "extraprovincial", "numéro d'entreprise", "numero d'entreprise", "enregistr"],
  tax: ["taxe", "impôt", "impot", "tvh", "tps", "tvp", "tvq", "droits de douane", "tarif", "douane", "aceum"],
  partners: ["partenaire", "distributeur", "distribution", "agent", "revendeur", "logistique", "entrepôt", "entrepot", "courtier", "présentation", "presentation"],
  costs: ["coût", "cout", "budget", "prix", "frais", "combien", "cher", "capital", "dépense", "depense", "estimation"],
  "province-choice": ["quelle province", "où devrions", "ou devrions", "ontario", "colombie", "alberta", "toronto", "vancouver", "calgary", "meilleure province", "commencer"],
  timeline: ["combien de temps", "délai", "delai", "calendrier", "semaines", "mois", "rapide", "quand", "durée", "duree", "échéancier", "echeancier"],
  employment: ["employé", "employe", "embauche", "embaucher", "paie", "personnel", "permis de travail", "visa", "immigration", "cnesst", "travail", "main-d'œuvre"],
};
